export interface GetDataCompany {
    reason: string,
    fantasyName: string,
    cnpj: string,
    street: string,
    number: string,
    district: string,
    cep: string,
    city: string,
    uf: string,
    phone1: string,
    phone2: string,
    imagem: string,
    observation: string,
    clauses: string,
}